CREATE TABLE `CNF_CUSTOMER_MESSAGE` (
    `CUSTOMER_MESSAGE_ID` bigint(20) NOT NULL,
    `SUBMIT_DATE` datetime DEFAULT NULL,
    `DATE_UPDATED` datetime DEFAULT NULL,
    `CUSTOMER_SENDER` bigint(20) NOT NULL,
    `CUSTOMER_DESTINATION` bigint(20) NOT NULL,
    `MESSAGE` longtext,
    PRIMARY KEY (`CUSTOMER_MESSAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;